"""Walk-forward backtest of the core-CPI tree over the last 12 resolvable prints.

For each target month m, the model is authored exactly as it would have been
live: weights fit on data through m-1, assumptions from the trailing 12 valid
months through m-1 (same code path as scripts/author_cpi.py — no lookahead).
Baselines: naive-last (previous valid core m/m) and trailing-6m mean.

Honesty rule (keel-v2 §9.2): the report is written as computed. If the tree
loses to the baselines, that is the finding — do not tune until it looks good.

Run:  uv run python scripts/backtest_cpi.py
Writes docs/backtest-cpi.md.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from waterline.cpi_author import AuthoringError, author_assumptions, fit_weights
from waterline.engine import run
from waterline.ingest.bls import SERIES, fetch_levels, load_env_key, mom
from waterline.model import build_model

N_TARGETS = 12
SEED = 20260702


def prev_period(p: str) -> str:
    y, m = int(p[:4]), int(p[5:])
    return f"{y - 1}-12" if m == 1 else f"{y}-{m - 1:02d}"


def main() -> int:
    key = load_env_key(ROOT)
    levels = fetch_levels(
        list(SERIES.values()), 2018, 2026, key=key, cache_dir=ROOT / "data/bls"
    )
    moms = {name: mom(levels[sid]) for name, sid in SERIES.items()}
    core = moms["core_cpi"]
    targets = sorted(core)[-N_TARGETS:]

    rows = []
    for t in targets:
        as_of = prev_period(t)
        try:
            fit = fit_weights(moms, as_of=as_of)
            assumptions = author_assumptions(moms, as_of=as_of)
        except AuthoringError as e:
            print(f"{t}: skipped ({e})")
            continue
        doc = {
            "name": f"backtest-{t}",
            "output": "core_cpi_mom",
            "nodes": {
                **{
                    f"{c}_mom": {"type": "assumption", "value": spec["value"]}
                    for c, spec in assumptions.items()
                },
                "decomposition_resid": {
                    "type": "assumption",
                    "value": {"normal": {"mean": 0.0, "sd": fit.resid_std}},
                },
                "core_cpi_mom": {
                    "type": "transform",
                    "fn": "weighted_sum",
                    "inputs": {
                        **{f"{c}_mom": w for c, w in fit.weights.items()},
                        "decomposition_resid": 1.0,
                    },
                },
            },
        }
        res = run(build_model(doc), seed=SEED)
        p = res.percentiles()
        history = [core[q] for q in sorted(core) if q <= as_of]
        rows.append({
            "period": t,
            "p10": p["p10"], "p50": p["p50"], "p90": p["p90"],
            "actual": core[t],
            "hit": p["p10"] <= core[t] <= p["p90"],
            "naive_last": history[-1],
            "trailing6": float(np.mean(history[-6:])),
        })

    n = len(rows)
    mae = lambda k: float(np.mean([abs(r[k] - r["actual"]) for r in rows]))  # noqa: E731
    mae_model, mae_naive, mae_t6 = mae("p50"), mae("naive_last"), mae("trailing6")
    coverage = sum(r["hit"] for r in rows) / n
    bias = float(np.mean([r["p50"] - r["actual"] for r in rows]))

    lines = [
        "# Core CPI m/m — walk-forward backtest",
        "",
        f"*Generated by scripts/backtest_cpi.py on {date.today().isoformat()}; "
        f"seed {SEED}; {n} resolvable prints (Oct/Nov 2025 are void — see docs/verify-cpi.md).*",
        "",
        "| period | p10 | p50 | p90 | actual | in 80% interval | naive-last | trailing-6m |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['period']} | {r['p10']:+.3f} | {r['p50']:+.3f} | {r['p90']:+.3f} "
            f"| {r['actual']:+.3f} | {'yes' if r['hit'] else 'NO'} "
            f"| {r['naive_last']:+.3f} | {r['trailing6']:+.3f} |"
        )
    lines += [
        "",
        "## Summary",
        "",
        f"- MAE of model p50: **{mae_model:.4f} pp**",
        f"- MAE of naive-last baseline: {mae_naive:.4f} pp",
        f"- MAE of trailing-6m-mean baseline: {mae_t6:.4f} pp",
        f"- 80% interval coverage: **{coverage:.0%}** (nominal 80%)",
        f"- Bias (p50 minus actual): {bias:+.4f} pp",
        "",
        "Verdict written as computed: the tree "
        + (
            "beats both baselines on MAE."
            if mae_model < min(mae_naive, mae_t6)
            else "does NOT beat "
            + (
                "either baseline"
                if mae_model >= max(mae_naive, mae_t6)
                else "the stronger baseline"
            )
            + " on MAE. Its value at this stage is the decomposition and the interval, "
            "not point accuracy; the news-analyst bot (Milestone 5) must earn the difference."
        ),
    ]
    out = ROOT / "docs" / "backtest-cpi.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"\nwrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
